Region: XXX_GTC_AWS_REGION_XXX
Image:
  Os: ubuntu2004
HeadNode:
  InstanceType: m5.xlarge
  Networking:
    SubnetId: XXX_GTC_SUBNET_ID_XXX
    ElasticIp: true
  Ssh:
    KeyName: XXX_GTC_KEY_NAME_XXX
  Dcv:
    Enabled: true
  CustomActions:
    OnNodeConfigured:
      Script: XXX_GTC_POST_INSTALL_XXX
      Args:
        - XXX_GTC_POST_INSTALL_ARG1_XXX
        - XXX_GTC_POST_INSTALL_ARG2_XXX
  Iam:
    S3Access:
    - BucketName: XXX_GTC_S3_NAME_XXX
      EnableWriteAccess: true
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: g5-vcpu192-gpu8
    CapacityType: ONDEMAND
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: g5-48xlarge
      InstanceType: g5.48xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: g5-vcpu192-gpu8-spot
    CapacityType: SPOT
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: g5-48xlarge-spot
      InstanceType: g5.48xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: g5-vcpu96-gpu4
    CapacityType: ONDEMAND
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: g5-24xlarge
      InstanceType: g5.24xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: g5-vcpu96-gpu4-spot
    CapacityType: SPOT
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: g5-24xlarge-spot
      InstanceType: g5.24xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: g5-vcpu48-gpu4
    CapacityType: ONDEMAND
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: g5-12xlarge
      InstanceType: g5.12xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: g5-vcpu48-gpu4-spot
    CapacityType: SPOT
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: g5-12xlarge-spot
      InstanceType: g5.12xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: g5-vcpu64-gpu1
    CapacityType: ONDEMAND
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: g5-16xlarge
      InstanceType: g5.16xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: g5-vcpu32-gpu1
    CapacityType: ONDEMAND
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: g5-8xlarge
      InstanceType: g5.8xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: g4dn-vcpu96-gpu8
    CapacityType: ONDEMAND
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: g4dn-metal
      InstanceType: g4dn.metal
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: g4dn-vcpu96-gpu8-spot
    CapacityType: SPOT
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: g4dn-metal-spot
      InstanceType: g4dn.metal
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: g4dn-vcpu48-gpu4
    CapacityType: ONDEMAND
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: g4dn-12xlarge
      InstanceType: g4dn.12xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: g4dn-vcpu48-gpu4-spot
    CapacityType: SPOT
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: g4dn-12xlarge-spot
      InstanceType: g4dn.12xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: g4dn-vcpu32-gpu1
    CapacityType: ONDEMAND
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: g4dn-8xlarge
      InstanceType: g4dn.8xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: c5d-vcpu96-gpu0
    CapacityType: ONDEMAND
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
    ComputeResources:
    - Name: c5d-24xlarge
      InstanceType: c5d.24xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: false
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: c6i-vcpu128-gpu0
    CapacityType: ONDEMAND
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: c6i-32xlarge
      InstanceType: c6i.32xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: c6i-vcpu128-gpu0-spot
    CapacityType: SPOT
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: c6i-32xlarge-spot
      InstanceType: c6i.32xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: m6i-vcpu128-gpu0
    CapacityType: ONDEMAND
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: m6i-32xlarge
      InstanceType: m6i.32xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: m6i-vcpu128-gpu0-spot
    CapacityType: SPOT
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: m6i-32xlarge-spot
      InstanceType: m6i.32xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: r6i-vcpu128-gpu0
    CapacityType: ONDEMAND
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: r6i-32xlarge
      InstanceType: r6i.32xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: r6i-vcpu128-gpu0-spot
    CapacityType: SPOT
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: r6i-32xlarge-spot
      InstanceType: r6i.32xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: c7i-vcpu192-gpu0
    CapacityType: ONDEMAND
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: c7i-48xlarge
      InstanceType: c7i.48xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: c7i-vcpu192-gpu0-spot
    CapacityType: SPOT
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: c7i-48xlarge-spot
      InstanceType: c7i.48xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: m7i-vcpu192-gpu0
    CapacityType: ONDEMAND
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: m7i-48xlarge
      InstanceType: m7i.48xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: m7i-vcpu192-gpu0-spot
    CapacityType: SPOT
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: m7i-48xlarge-spot
      InstanceType: m7i.48xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: r7i-vcpu192-gpu0
    CapacityType: ONDEMAND
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: r7i-48xlarge
      InstanceType: r7i.48xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
  - Name: r7i-vcpu192-gpu0-spot
    CapacityType: SPOT
    Networking:
      SubnetIds:
      - XXX_GTC_SUBNET_ID_XXX
      AssignPublicIp: true
      PlacementGroup:
        Enabled: true
    ComputeResources:
    - Name: r7i-48xlarge-spot
      InstanceType: r7i.48xlarge
      MaxCount: XXX_GTC_COMPUTE_RESOURCE_MAX_COUNT_XXX
      Efa:
        Enabled: true
        GdrSupport: false
    CustomActions:
      OnNodeConfigured:
        Script: XXX_GTC_POST_INSTALL_XXX
        Args:
          - XXX_GTC_POST_INSTALL_ARG1_XXX
          - XXX_GTC_POST_INSTALL_ARG2_XXX
    Iam:
      S3Access:
      - BucketName: XXX_GTC_S3_NAME_XXX
        EnableWriteAccess: true
SharedStorage:
- MountDir: /fsx
  Name: fsx-scratch
  StorageType: FsxLustre
  FsxLustreSettings:
    StorageCapacity: XXX_GTC_FSX_MB_CAPACITY_XXX
    DeploymentType: SCRATCH_2
    ExportPath: s3://XXX_GTC_S3_NAME_XXX
    ImportPath: s3://XXX_GTC_S3_NAME_XXX
Monitoring:
  Logs:
    CloudWatch:
      Enabled: true
      RetentionInDays: 180
      DeletionPolicy: Retain
Tags:
- Key: XXX_GTC_TAG_KEY_IAMUSER_XXX
  Value: XXX_GTC_IAM_USER_NAME_XXX
- Key: XXX_GTC_TAG_KEY_METHOD_XXX
  Value: XXX_GTC_METHOD_NAME_XXX
- Key: XXX_GTC_TAG_KEY_PROJECT_XXX
  Value: XXX_GTC_PROJECT_NAME_XXX
- Key: XXX_GTC_TAG_KEY_ACCOUNT_XXX
  Value: "XXX_GTC_ACCOUNT_ID_XXX"
- Key: XXX_GTC_TAG_KEY_USER_XXX
  Value: XXX_GTC_IAM_USER_NAME_XXX
- Key: XXX_GTC_TAG_KEY_SERVICE_XXX
  Value: XXX_GTC_METHOD_NAME_XXX
- Key: XXX_GTC_TAG_KEY_TEAM_XXX
  Value: XXX_GTC_PROJECT_NAME_XXX
